In [1]:
!which python

/c/ProgramData/Anaconda3/python


In [2]:
from controller.game import GameController
from view.consolegui import ConsoleGui
from model.humanplayer import HumanPlayer
from model.bag import Bag
from model.config import Direction
from model.row import Row
import numpy as np
from model.config import LETTER_VALUES, NO_CROSS_WORD, RACK_SIZE, BONUS

In [3]:
players = [None, None]
bag = Bag()
game = GameController(players, bag)
gui = ConsoleGui(game)
player1 = HumanPlayer(bag, gui, "Player 1")
player2 = HumanPlayer(bag, gui, "Player 2")
game.players = [player1, player2]
game.active_player = player2
board = game.board
lex = game.lexicon
validator = game.validator
board

GameBoard object:
     A B C D E F G H I J K L M N O
   + - - - - - - - - - - - - - - - +
 1 | = . . ' . . . = . . . ' . . = |
 2 | . - . . . " . . . " . . . - . |
 3 | . . - . . . ' . ' . . . - . . |
 4 | ' . . - . . . ' . . . - . . ' |
 5 | . . . . - . . . . . - . . . . |
 6 | . " . . . " . . . " . . . " . |
 7 | . . ' . . . ' . ' . . . ' . . |
 8 | = . . ' . . . * . . . ' . . = |
 9 | . . ' . . . ' . ' . . . ' . . |
10 | . " . . . " . . . " . . . " . |
11 | . . . . - . . . . . - . . . . |
12 | . . . - . . . ' . . . - . . . |
13 | ' . - . . . ' . ' . . . - . ' |
14 | . - . . . " . . . " . . . - . |
15 | = . . ' . . . = . . . ' . . = |
   + - - - - - - - - - - - - - - - +
     A B C D E F G H I J K L M N O

In [4]:
player2.rack

Rack object containing the following tiles:
ITOIIQO

In [5]:
move = gui.parse_move_string('G8HQI')

In [6]:
print(move)

Move: G8, Horizontal, tiles: QI, forms word: , score: None


In [7]:
validator.is_valid(move)

True

In [8]:
tile_values = [LETTER_VALUES[(ord(t)-64)] for t in move.tiles]

In [9]:
move.score

22.0

In [10]:
tile_values

[10, 1]

In [11]:
squares_in_whole_word = move.row.squares_in_word(move.start_index)
squares_in_whole_word

array([7, 8], dtype=int64)

In [12]:
np.put(move.row.existing_letter_scores, move.played_squares, tile_values)

In [13]:
board

GameBoard object:
     A B C D E F G H I J K L M N O
   + - - - - - - - - - - - - - - - +
 1 | = . . ' . . . = . . . ' . . = |
 2 | . - . . . " . . . " . . . - . |
 3 | . . - . . . ' . ' . . . - . . |
 4 | ' . . - . . . ' . . . - . . ' |
 5 | . . . . - . . . . . - . . . . |
 6 | . " . . . " . . . " . . . " . |
 7 | . . ' . . . ' . ' . . . ' . . |
 8 | = . . ' . . Q I . . . ' . . = |
 9 | . . ' . . . ' . ' . . . ' . . |
10 | . " . . . " . . . " . . . " . |
11 | . . . . - . . . . . - . . . . |
12 | . . . - . . . ' . . . - . . . |
13 | ' . - . . . ' . ' . . . - . ' |
14 | . - . . . " . . . " . . . - . |
15 | = . . ' . . . = . . . ' . . = |
   + - - - - - - - - - - - - - - - +
     A B C D E F G H I J K L M N O

In [14]:
gui.describe_square('G9')

hook_squares:               False
word_multiplier:            1
letter_multiplier:          2
existing_letters:           none
existing_letter_scores:     0
this_row_crosschecks:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
this_row_crosschecks:       ABCDEFGHIJKLMNOPQRSTUVWXYZ
orthogonal_row_crosschecks: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
orthogonal_row_crosschecks: ABCDEFGHIJKLMNOPQRSTUVWXYZ
this_row_cross_scores:      -1
column_play_scores:         -1


In [15]:
game.execute_move(move)

In [16]:
row = move.row
row

row object:
 8 | = . . ' . * Q I * . . ' . . = |

In [17]:
row.hook_squares

array([False, False, False, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False])

In [18]:
gui.describe_square('I8')

hook_squares:               True
word_multiplier:            1
letter_multiplier:          1
existing_letters:           none
existing_letter_scores:     0
this_row_crosschecks:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
this_row_crosschecks:       ABCDEFGHIJKLMNOPQRSTUVWXYZ
orthogonal_row_crosschecks: [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1]
orthogonal_row_crosschecks: NS
this_row_cross_scores:      -1
column_play_scores:         11


In [19]:
col = board.get_row(9,Direction.VERTICAL)

In [20]:
col

row object:
 I | . . ' . . . ' * ' . . . ' . . |

In [21]:
col.this_row_crosschecks

array([         0, 4294967295, 4294967295, 4294967295, 4294967295,
       4294967295, 4294967295, 4294967295, 4161290241, 4294967295,
       4294967295, 4294967295, 4294967295, 4294967295, 4294967295,
       4294967295,          0], dtype=uint32)

In [22]:
print(move)

Move: G8, Horizontal, tiles: QI, forms word: QI, score: 22.0


In [23]:
move

Move object:
Move: G8, Horizontal, tiles: QI, forms word: QI, score: 22.0

In [24]:
board

GameBoard object:
     A B C D E F G H I J K L M N O
   + - - - - - - - - - - - - - - - +
 1 | = . . ' . . . = . . . ' . . = |
 2 | . - . . . " . . . " . . . - . |
 3 | . . - . . . ' . ' . . . - . . |
 4 | ' . . - . . . ' . . . - . . ' |
 5 | . . . . - . . . . . - . . . . |
 6 | . " . . . " . . . " . . . " . |
 7 | . . ' . . . * * ' . . . ' . . |
 8 | = . . ' . * Q I * . . ' . . = |
 9 | . . ' . . . * * ' . . . ' . . |
10 | . " . . . " . . . " . . . " . |
11 | . . . . - . . . . . - . . . . |
12 | . . . - . . . ' . . . - . . . |
13 | ' . - . . . ' . ' . . . - . ' |
14 | . - . . . " . . . " . . . - . |
15 | = . . ' . . . = . . . ' . . = |
   + - - - - - - - - - - - - - - - +
     A B C D E F G H I J K L M N O

In [25]:
False is not None

True

In [26]:

None is not None

False

In [27]:
'CaT' in lex


True

In [37]:
x = [1,2,0,4,5]

In [42]:
y = np.where(x)

In [39]:
y

(array([0, 1, 3, 4], dtype=int64),)

In [40]:
x[0] = 0
x

[0, 2, 0, 4, 5]

In [43]:
y

(array([1, 3, 4], dtype=int64),)

In [47]:
ord('@')

64

In [48]:
'a'.upper()

'A'

In [49]:
'hexact' in lex


True

In [50]:
'paramo' in lex


True

In [51]:
'overlya' in lex


False