In [1]:
from fastai.imports import *
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *


C:\Users\richard\AppData\Local\conda\conda\envs\fastai\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [4]:
PATH = 'data/'
sz = 256

In [5]:
arch=resnet18
data = ImageClassifierData.from_paths(PATH, tfms=tfms_from_model(arch, sz))
learn = ConvLearner.pretrained(arch, data, precompute=False)
learn.load('epoch10')


In [9]:
#Then to predict the class of an image:
trn_tfms, val_tfms = tfms_from_model(arch,sz)
img = open_image('data/test1/option_0000.png')
im = val_tfms(img)
preds = learn.predict_array(im[None])
print(np.argmax(preds))

1


In [14]:
os.listdir('data/test1')

['option_0000.png',
 'option_0001.png',
 'option_0002.png',
 'option_0003.png',
 'option_0004.png',
 'option_0005.png',
 'option_0006.png',
 'option_0007.png',
 'option_0008.png',
 'option_0009.png',
 'option_0010.png',
 'option_0011.png',
 'option_0012.png',
 'option_0013.png',
 'option_0014.png',
 'option_0015.png',
 'option_0016.png',
 'option_0017.png',
 'option_0018.png',
 'option_0019.png',
 'option_0020.png',
 'option_0021.png',
 'option_0022.png',
 'option_0023.png',
 'option_0024.png',
 'option_0025.png',
 'option_0026.png',
 'option_0027.png',
 'option_0028.png',
 'option_0029.png',
 'option_0030.png',
 'option_0031.png',
 'option_0032.png',
 'option_0033.png',
 'option_0034.png',
 'option_0035.png',
 'option_0036.png',
 'option_0037.png',
 'option_0038.png',
 'option_0039.png',
 'option_0040.png',
 'option_0041.png',
 'option_0042.png',
 'option_0043.png',
 'option_0044.png',
 'option_0045.png',
 'option_0046.png',
 'option_0047.png',
 'option_0048.png',
 'option_0049.png',


In [10]:
preds


array([[-3.74354, -0.02395]], dtype=float32)

In [11]:
??open_image()

In [12]:
learn.predict(is_test=True)

TypeError: 'NoneType' object is not iterable

In [17]:
from model.deepaiplayer import *

In [18]:
learn

Sequential(
  (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
  (2): ReLU(inplace)
  (3): MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), dilation=(1, 1), ceil_mode=False)
  (4): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True)
      (relu): ReLU(inplace)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d

In [19]:
images = [val_tfms(open_image('data/temp/' + file_name)) for file_name in os.listdir('data/temp')]

In [39]:
preds2 = [learn.predict_array(img[None])[0][0] for img in images]

In [42]:
np.argmax(preds2)

474

In [43]:
len(preds2)

547

In [33]:
preds[3][0]

array([-0.78221, -0.61137], dtype=float32)

In [28]:
img1

array([[[-2.1179 , -2.1179 , -2.1179 , ..., -2.1179 , -2.1179 , -2.1179 ],
        [-2.1179 , -2.1179 , -2.1179 , ..., -2.1179 , -2.1179 , -2.1179 ],
        [-2.1179 , -2.1179 , -2.1179 , ..., -2.1179 , -2.1179 , -2.1179 ],
        ...,
        [-2.1179 , -2.1179 , -2.1179 , ..., -2.1179 , -2.1179 , -2.1179 ],
        [-2.1179 , -2.1179 , -2.1179 , ..., -2.1179 , -2.1179 , -2.1179 ],
        [-2.1179 , -2.1179 , -2.1179 , ..., -2.1179 , -2.1179 , -2.1179 ]],

       [[-2.03571, -2.03571, -2.03571, ..., -2.03571, -2.03571, -2.03571],
        [-2.03571, -2.03571, -2.03571, ..., -2.03571, -2.03571, -2.03571],
        [-2.03571, -2.03571, -2.03571, ..., -2.03571, -2.03571, -2.03571],
        ...,
        [-2.03571, -2.03571, -2.03571, ...,  1.7458 ,  1.7458 ,  1.7458 ],
        [-2.03571, -2.03571, -2.03571, ...,  1.7458 ,  1.7458 ,  1.7458 ],
        [-2.03571, -2.03571, -2.03571, ...,  1.7458 ,  1.7458 ,  1.7458 ]],

       [[-0.39268, -0.39268, -0.39268, ..., -1.80444, -1.80444, -1.804