In [1]:
# auto reloading and inline display of matplotlib output:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from controller.game import GameController
from view.consolegui import ConsoleGui
from view.view import View
from model.humanplayer import HumanPlayer
from model.deepaiplayer import DeepAiPlayer
from model.aiplayer import AiPlayer
from model.bag import Bag
from model.config import Direction
from model.row import Row
import numpy as np
from model.config import LETTER_VALUES, NO_CROSS_WORD, RACK_SIZE, BONUS

C:\Users\richard\AppData\Local\conda\conda\envs\fastai\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [3]:
def new_game():
    players = [None, None]
    bag = Bag()
    game = GameController(players, bag)
    gui = View(game) # headless view
    player1 = DeepAiPlayer(game, gui, "Deep AI Player 1")
    player2 = AiPlayer(game, gui, "AI Player 2")
    game.players = [player1, player2]
    return (game, player1, player2)

In [ ]:
winners = []
move_lists = {}

for i in range(100):
    game, player1, player2 = new_game()
    move_lists[i] = game.run_game()
    if player1.score > player2.score:
        winners.append(1)
    elif player2.score > player1.score:
        winners.append(2)
    else:
        winners.append(0) # draw
        
    x = np.array(winners)
    print ("After " + str(len(winners)) + " games: (draw, player1, player2) = " 
           + str((len(x[x==0]), len(x[x==1]), len(x[x==2]))))

Waiting for players
Starting game
('AI Player 2', 'O', 'VIOLAS', Move object:
Move: D8, Horizontal, tiles: VIOLAS, score: 26.0)
('Deep AI Player 1', 'X', 'OLEATES', Move object:
Move: G7, Vertical, tiles: OEATES, score: 10.0)
('AI Player 2', '-', 'ATEMOYA', Move object:
Move: I7, Horizontal, tiles: ATEMOYA, score: 67.0)
('Deep AI Player 1', 'PF', 'SEXPOT', Move object:
Move: H13, Horizontal, tiles: EXPOT, score: 23.0)
('AI Player 2', 'UEU', 'IDEE', Move object:
Move: L8, Horizontal, tiles: IDEE, score: 37.0)
('Deep AI Player 1', 'PF', 'VITTAE', Move object:
Move: D9, Vertical, tiles: ITTAE, score: 18.0)
('AI Player 2', 'UUDI', 'HEED', Move object:
Move: H12, Vertical, tiles: HED, score: 45.0)
('Deep AI Player 1', 'NHJ', 'PREIF', Move object:
Move: E5, Vertical, tiles: PREF, score: 25.0)
('AI Player 2', 'UU', 'DINED', Move object:
Move: K12, Horizontal, tiles: DINED, score: 25.0)
('Deep AI Player 1', 'NHJOe', 'WIFIE', Move object:
Move: C9, Horizontal, tiles: WI, score: 17.0)
('AI Playe

Move 4: AI Player 2 - rack leave: G, made word: WAFTURE - Move: G5, Vertical, tiles: WAFURE, score: 23.0
Move 5: Deep AI Player 1 - rack leave: LPRW, made word: FeRM - Move: F6, Vertical, tiles: FeM, score: 37.0
Move 6: AI Player 2 - rack leave: GTVDD, made word: XIS - Move: F14, Horizontal, tiles: XI, score: 26.0
Move 7: Deep AI Player 1 - rack leave: LRWB, made word: ZEP - Move: H4, Vertical, tiles: ZEP, score: 37.0
Move 8: AI Player 2 - rack leave: GDDR, made word: VAT - Move: I3, Vertical, tiles: VAT, score: 27.0
Move 9: Deep AI Player 1 - rack leave: RWBLK, made word: WETLY - Move: J5, Horizontal, tiles: LY, score: 22.0
Move 10: AI Player 2 - rack leave: -, made word: REBADGED - Move: D6, Vertical, tiles: READGED, score: 76.0
Move 11: Deep AI Player 1 - rack leave: K, made word: BOWLER - Move: C2, Vertical, tiles: BOWLER, score: 29.0
Move 12: AI Player 2 - rack leave: EON, made word: QUIT - Move: D15, Horizontal, tiles: QUIT, score: 34.0
Move 13: Deep AI Player 1 - rack leave: PIU

Move: M1, Horizontal, tiles: WED, score: 43.0)
('Deep AI Player 1', 'AAARI', 'JEDI', Move object:
Move: J2, Horizontal, tiles: JE, score: 28.0)
('AI Player 2', 'QR', 'GOWAN', Move object:
Move: E11, Horizontal, tiles: GOWAN, score: 32.0)
('Deep AI Player 1', 'AAA', 'RIMA', Move object:
Move: G3, Horizontal, tiles: RIMA, score: 19.0)
('AI Player 2', 'QOI', 'REIVE', Move object:
Move: H1, Vertical, tiles: REVE, score: 36.0)
('Deep AI Player 1', 'AACB', 'LAX', Move object:
Move: F12, Horizontal, tiles: LAX, score: 48.0)
('AI Player 2', 'QIOO', 'KOR', Move object:
Move: F6, Horizontal, tiles: KOR, score: 26.0)
('Deep AI Player 1', 'AACBUD', 'JEDIS', Move object:
Move: N2, Horizontal, tiles: S, score: 30.0)
('AI Player 2', 'QIOT', 'RONT', Move object:
Move: J4, Horizontal, tiles: ROT, score: 21.0)
('Deep AI Player 1', 'AACBA', 'DUE', Move object:
Move: F2, Horizontal, tiles: DU, score: 10.0)
('AI Player 2', 'QOT', 'GLID', Move object:
Move: C13, Horizontal, tiles: GLID, score: 17.0)
('Deep 

Move 2: Deep AI Player 1 - rack leave: AIZJs, made word: XI - Move: C9, Horizontal, tiles: XI, score: 23.0
Move 3: AI Player 2 - rack leave: DD, made word: ATTAR - Move: F9, Horizontal, tiles: ATTAR, score: 20.0
Move 4: Deep AI Player 1 - rack leave: AJAI, made word: sIZE - Move: E5, Vertical, tiles: sIZ, score: 24.0
Move 5: AI Player 2 - rack leave: R, made word: ELIDED - Move: A10, Horizontal, tiles: ELIDED, score: 42.0
Move 6: Deep AI Player 1 - rack leave: JC, made word: LAARI - Move: D1, Vertical, tiles: LAARI, score: 13.0
Move 7: AI Player 2 - rack leave: RQH, made word: MIAOW - Move: B2, Horizontal, tiles: MIOW, score: 36.0
Move 8: Deep AI Player 1 - rack leave: JC, made word: EUOUAE - Move: A5, Vertical, tiles: EUOUA, score: 18.0
Move 9: AI Player 2 - rack leave: RQGCD, made word: HM - Move: B6, Vertical, tiles: HM, score: 32.0
Move 10: Deep AI Player 1 - rack leave: JCE, made word: LOONS - Move: E1, Horizontal, tiles: OONS, score: 22.0
Move 11: AI Player 2 - rack leave: QG, ma

Move: J9, Vertical, tiles: AV, score: 24.0)
('Deep AI Player 1', 'ODO', 'QUIRE', Move object:
Move: H1, Vertical, tiles: QUIE, score: 42.0)
('AI Player 2', 'BNVA', 'GENA', Move object:
Move: G3, Vertical, tiles: GNA, score: 23.0)
('Deep AI Player 1', 'OWLU', 'DOZE', Move object:
Move: A7, Horizontal, tiles: DOZ, score: 24.0)
('AI Player 2', 'BNVOG', 'AX', Move object:
Move: A8, Horizontal, tiles: AX, score: 45.0)
('Deep AI Player 1', 'LUYRR', 'OW', Move object:
Move: A6, Horizontal, tiles: OW, score: 38.0)
('AI Player 2', 'BVOW', 'INGS', Move object:
Move: I1, Vertical, tiles: ING, score: 27.0)
('Deep AI Player 1', 'Y', 'RULIER', Move object:
Move: F11, Horizontal, tiles: RULIER, score: 19.0)
('AI Player 2', 'B', 'REWOVE', Move object:
Move: J12, Horizontal, tiles: REWOVE, score: 36.0)
('Deep AI Player 1', 'OMO', 'YIDS', Move object:
Move: G13, Horizontal, tiles: YIDS, score: 23.0)
('AI Player 2', 'BBDPN', 'INK', Move object:
Move: H14, Vertical, tiles: NK, score: 21.0)
('Deep AI Playe

Move 8: Deep AI Player 1 - rack leave: ACT, made word: MOCK - Move: D10, Vertical, tiles: MOCK, score: 28.0
Move 9: AI Player 2 - rack leave: NTIO, made word: ZEE - Move: H1, Vertical, tiles: ZEE, score: 38.0
Move 10: Deep AI Player 1 - rack leave: CT, made word: KeDDAH - Move: E13, Horizontal, tiles: eDDAH, score: 20.0
Move 11: AI Player 2 - rack leave: TNN, made word: NGAIO - Move: H11, Vertical, tiles: NGIO, score: 24.0
Move 12: Deep AI Player 1 - rack leave: CIH, made word: WOOTZ - Move: D1, Horizontal, tiles: WOOT, score: 21.0
Move 13: AI Player 2 - rack leave: NNTE, made word: QAT - Move: B1, Vertical, tiles: QAT, score: 26.0
Move 14: Deep AI Player 1 - rack leave: CD, made word: INSHIP - Move: G11, Horizontal, tiles: ISHIP, score: 22.0
Move 15: AI Player 2 - rack leave: NNR, made word: WEET - Move: B10, Vertical, tiles: WEET, score: 31.0
Move 16: Deep AI Player 1 - rack leave: J, made word: SOUCED - Move: J10, Horizontal, tiles: SOUCED, score: 26.0
Move 17: AI Player 2 - rack le

Move: C10, Vertical, tiles: IRPS, score: 16.0)
('AI Player 2', 'CMMA', 'TOWN', Move object:
Move: L6, Horizontal, tiles: TOW, score: 40.0)
('Deep AI Player 1', 'BV', 'INTRON', Move object:
Move: I3, Vertical, tiles: INTRO, score: 8.0)
('AI Player 2', 'MMO', 'CAPIZ', Move object:
Move: A12, Horizontal, tiles: CAIZ, score: 42.0)
('Deep AI Player 1', 'V', 'ABUSERS', Move object:
Move: G10, Vertical, tiles: BUSERS, score: 10.0)
('AI Player 2', 'OUI', 'MIASM', Move object:
Move: D15, Horizontal, tiles: MIAM, score: 36.0)
('Deep AI Player 1', 'VN', 'LUNGER', Move object:
Move: F11, Horizontal, tiles: LNGER, score: 14.0)
('AI Player 2', 'UI', 'NOCEBO', Move object:
Move: A10, Vertical, tiles: NOEBO, score: 30.0)
('Deep AI Player 1', 'L', 'VENTRED', Move object:
Move: F13, Horizontal, tiles: VNTRED, score: 12.0)
('AI Player 2', 'UID', 'AGHA', Move object:
Move: H1, Vertical, tiles: AGHA, score: 35.0)
('Deep AI Player 1', 'LL', 'OUTDO', Move object:
Move: J1, Vertical, tiles: OUTDO, score: 20.0

Move 14: Deep AI Player 1 - rack leave: AVI, made word: JEUX - Move: D1, Vertical, tiles: JEUX, score: 74.0
Move 15: AI Player 2 - rack leave: QTe, made word: TOSSY - Move: M2, Vertical, tiles: OSSY, score: 47.0
Move 16: Deep AI Player 1 - rack leave: AG, made word: VALID - Move: B2, Vertical, tiles: VALID, score: 51.0
Move 17: AI Player 2 - rack leave: QR, made word: UNKeNT - Move: A10, Vertical, tiles: UNeNT, score: 27.0
Move 18: Deep AI Player 1 - rack leave: AGC, made word: INGAN - Move: H10, Horizontal, tiles: IGAN, score: 23.0
Move 19: AI Player 2 - rack leave: QIAIU, made word: ORBY - Move: J5, Horizontal, tiles: OR, score: 23.0
Move 20: Deep AI Player 1 - rack leave: CDAF, made word: EGAL - Move: M8, Horizontal, tiles: GAL, score: 15.0
Move 21: AI Player 2 - rack leave: IO, made word: QUALIA - Move: N6, Vertical, tiles: QULIA, score: 37.0
Move 22: Deep AI Player 1 - rack leave: CA, made word: FED - Move: J12, Horizontal, tiles: FED, score: 32.0
Move 23: AI Player 2 - rack leave

Move: I14, Horizontal, tiles: ABA, score: 26.0)
('Deep AI Player 1', 'ZTL', 'DURST', Move object:
Move: A11, Vertical, tiles: DURS, score: 7.0)
('AI Player 2', 'IV', 'sEN', Move object:
Move: O8, Vertical, tiles: sEN, score: 46.0)
('Deep AI Player 1', 'L', 'ZIT', Move object:
Move: J2, Vertical, tiles: ZT, score: 32.0)
('AI Player 2', 'V', 'IO', Move object:
Move: N2, Horizontal, tiles: I, score: 8.0)
('Deep AI Player 1', '-', 'LOY', Move object:
Move: F12, Vertical, tiles: L, score: 6.0)
Game ended:
Final scores:

Deep AI Player 1 scored 316.0
AI Player 2 scored 437.0

Move list:
Move 1: Deep AI Player 1 - rack leave: XI, made word: REHAB - Move: D8, Horizontal, tiles: REHAB, score: 22.0
Move 2: AI Player 2 - rack leave: CMT, made word: WILD - Move: G9, Horizontal, tiles: WILD, score: 26.0
Move 3: Deep AI Player 1 - rack leave: OI, made word: AXION - Move: J8, Horizontal, tiles: AXION, score: 16.0
Move 4: AI Player 2 - rack leave: CI, made word: METED - Move: C7, Horizontal, tiles: ME

Move: A8, Horizontal, tiles: RIVO, score: 28.0)
('AI Player 2', '-', 'CANNIBAL', Move object:
Move: B4, Vertical, tiles: CANNBAL, score: 66.0)
('Deep AI Player 1', 'GKT', 'TOYER', Move object:
Move: E3, Vertical, tiles: TOYE, score: 16.0)
('AI Player 2', 'UUO', 'TEIN', Move object:
Move: D2, Vertical, tiles: TEIN, score: 19.0)
('Deep AI Player 1', 'GD', 'KRAFT', Move object:
Move: I7, Horizontal, tiles: KRAFT, score: 43.0)
('AI Player 2', 'UOO', 'HUIS', Move object:
Move: A1, Horizontal, tiles: HUIS, score: 30.0)
('Deep AI Player 1', 'GU', 'TETRODE', Move object:
Move: C3, Horizontal, tiles: TRODE, score: 20.0)
('AI Player 2', 'UOOA', 'WAE', Move object:
Move: D12, Horizontal, tiles: WAE, score: 27.0)
('Deep AI Player 1', 'GIECE', 'OUD', Move object:
Move: H1, Vertical, tiles: OU, score: 12.0)
('AI Player 2', 'UOO', 'STOAE', Move object:
Move: G10, Horizontal, tiles: SOAE, score: 36.0)
('Deep AI Player 1', 'G', 'DECIME', Move object:
Move: A10, Vertical, tiles: DECIME, score: 47.0)
('A

Move 11: Deep AI Player 1 - rack leave: AUUF, made word: JEED - Move: A15, Horizontal, tiles: JED, score: 42.0
Move 12: AI Player 2 - rack leave: -, made word: TURGIDER - Move: O2, Vertical, tiles: TURGIDR, score: 61.0
Move 13: Deep AI Player 1 - rack leave: UFO, made word: PULA - Move: N1, Vertical, tiles: PULA, score: 20.0
Move 14: AI Player 2 - rack leave: AFY, made word: CHEWY - Move: K10, Vertical, tiles: HEWY, score: 37.0
Move 15: Deep AI Player 1 - rack leave: OE, made word: AURIFY - Move: F13, Horizontal, tiles: AURIF, score: 14.0
Move 16: AI Player 2 - rack leave: FDGL, made word: XRAY - Move: H12, Vertical, tiles: XAY, score: 66.0
Move 17: Deep AI Player 1 - rack leave: EO, made word: NOsEAN - Move: E4, Vertical, tiles: NOsEN, score: 13.0
Move 18: AI Player 2 - rack leave: GLT, made word: FIDO - Move: D1, Vertical, tiles: FIDO, score: 28.0
Move 19: Deep AI Player 1 - rack leave: VO, made word: TOWSE - Move: F1, Vertical, tiles: TOWSE, score: 15.0
Move 20: AI Player 2 - rack l

Move: H12, Horizontal, tiles: HOOEY, score: 39.0)
('Deep AI Player 1', 'BO', 'DEITY', Move object:
Move: J9, Horizontal, tiles: DEITY, score: 13.0)
('AI Player 2', 'UDGX', 'TIZ', Move object:
Move: H1, Vertical, tiles: TIZ, score: 48.0)
('Deep AI Player 1', '-', 'BONNIER', Move object:
Move: I11, Horizontal, tiles: BONNIER, score: 83.0)
('AI Player 2', 'DS', 'GUANXI', Move object:
Move: L4, Vertical, tiles: GUANX, score: 44.0)
('Deep AI Player 1', 'QIFWR', 'HEIL', Move object:
Move: H14, Vertical, tiles: IL, score: 21.0)
('AI Player 2', 'RU', 'DYNEINS', Move object:
Move: N8, Vertical, tiles: DNINS, score: 26.0)
('Deep AI Player 1', 'FWRWE', 'QI', Move object:
Move: O7, Vertical, tiles: QI, score: 42.0)
('AI Player 2', 'UVI', 'MARE', Move object:
Move: J2, Vertical, tiles: MARE, score: 40.0)
('Deep AI Player 1', 'WW', 'FORCES', Move object:
Move: D3, Vertical, tiles: FORCE, score: 25.0)
('AI Player 2', 'VIT', 'CUPS', Move object:
Move: M3, Vertical, tiles: CUPS, score: 25.0)
('Deep AI 

Move 20: Deep AI Player 1 - rack leave: QH, made word: ELVaN - Move: N1, Vertical, tiles: ELVaN, score: 19.0
Move 21: AI Player 2 - rack leave: -, made word: PILEI - Move: K1, Horizontal, tiles: PILI, score: 24.0
Move 22: Deep AI Player 1 - rack leave: QH, made word: n/a - Final score adjustment: -14
Move 23: AI Player 2 - rack leave: , made word: n/a - Final score adjustment: +14
After 19 games: (draw, player1, player2) = (0, 1, 18)
Waiting for players
Starting game
('AI Player 2', 'QD', 'AGENE', Move object:
Move: H8, Horizontal, tiles: AGENE, score: 14.0)
('Deep AI Player 1', 'N', 'PAROLE', Move object:
Move: C9, Horizontal, tiles: PAROLE, score: 14.0)
('AI Player 2', 'QDSSL', 'HA', Move object:
Move: F10, Horizontal, tiles: HA, score: 28.0)
('Deep AI Player 1', 'UN', 'YOKING', Move object:
Move: I3, Vertical, tiles: YOKIN, score: 19.0)
('AI Player 2', 'QDSLVT', 'YOKINGS', Move object:
Move: I9, Vertical, tiles: S, score: 26.0)
('Deep AI Player 1', '-', 'UNTWINED', Move object:
Move

Move: F15, Horizontal, tiles: ABA, score: 21.0)
Game ended:
Final scores:

Deep AI Player 1 scored 293.0
AI Player 2 scored 437.0

Move list:
Move 1: Deep AI Player 1 - rack leave: TL, made word: YONIC - Move: D8, Horizontal, tiles: YONIC, score: 28.0
Move 2: AI Player 2 - rack leave: -, made word: EMINENCE - Move: H2, Vertical, tiles: EMINENE, score: 63.0
Move 3: Deep AI Player 1 - rack leave: L, made word: VIDETTE - Move: G4, Horizontal, tiles: VDETTE, score: 22.0
Move 4: AI Player 2 - rack leave: II, made word: LEAFY - Move: J5, Horizontal, tiles: LEAFY, score: 35.0
Move 5: Deep AI Player 1 - rack leave: GA, made word: OUTLAY - Move: D3, Vertical, tiles: OUTLA, score: 18.0
Move 6: AI Player 2 - rack leave: IIWr, made word: POSY - Move: N2, Vertical, tiles: POS, score: 30.0
Move 7: Deep AI Player 1 - rack leave: GAO, made word: KEFIRS - Move: M3, Vertical, tiles: KIRS, score: 40.0
Move 8: AI Player 2 - rack leave: IIRR, made word: HeW - Move: O1, Vertical, tiles: HeW, score: 37.0
Mov

Move 26: AI Player 2 - rack leave: I, made word: n/a - Final score adjustment: -1
Move 27: Deep AI Player 1 - rack leave: , made word: n/a - Final score adjustment: +1
After 22 games: (draw, player1, player2) = (0, 1, 21)
Waiting for players
Starting game
('AI Player 2', 'C', 'WITANS', Move object:
Move: D8, Horizontal, tiles: WITANS, score: 26.0)
('Deep AI Player 1', 'IOAA', 'FEE', Move object:
Move: G7, Horizontal, tiles: FEE, score: 25.0)
('AI Player 2', 'CNV', 'WIDDY', Move object:
Move: E7, Vertical, tiles: WDDY, score: 26.0)
('Deep AI Player 1', 'IAA', 'SOUP', Move object:
Move: H6, Horizontal, tiles: SOUP, score: 14.0)
('AI Player 2', 'VUR', 'CODON', Move object:
Move: C9, Horizontal, tiles: COON, score: 26.0)
('Deep AI Player 1', 'IAA', 'CAUPS', Move object:
Move: C10, Vertical, tiles: AUPS, score: 18.0)
('AI Player 2', 'RDAU', 'GUV', Move object:
Move: J5, Horizontal, tiles: GUV, score: 25.0)
('Deep AI Player 1', 'AB', 'SAMITE', Move object:
Move: D13, Horizontal, tiles: AMITE

In [5]:
moves = player1.generate_all_moves()

In [6]:
player1.rack

Rack object containing the following tiles:
AGILPRZ

In [7]:
player1.generate_images(moves)

In [10]:
import os
image_paths = [player1.img_path + 'temp/' + file_name for file_name in os.listdir(player1.img_path + 'temp')]

In [12]:
from fastai.dataset import open_image
images = [player1.transforms(open_image(image_path)) for image_path in image_paths]

In [14]:
predictions = [np.exp(player1.learn.predict_array(img[None])[0][0]) for img in images]
predictions

In [19]:
np.argmax(predictions)
predictions[486]

0.4279545

In [18]:
player1.best_move(moves)

Move object:
Move: I3, Vertical, tiles: TABBID, score: 16.0

In [15]:
img = player1.transforms(open_image('data/temp/option_0043.png'))
pred = player1.learn.predict_array(img[None])[0][0]
pred

-4.6535335

In [16]:
np.exp(pred)

0.009527876

In [5]:
rack = player1.rack
rack

Rack object containing the following tiles:
@AEMQSY

In [6]:
player1

In [8]:
rack.rack_tiles[3] = 'g'

In [9]:
rack

Rack object containing the following tiles:
EGGHILg

In [10]:
'@' in rack

False

In [17]:
b = x>0
b

array([False,  True,  True,  True,  True,  True,  True,  True,  True, False])

In [21]:
print ("(draw, player1, player2) = " + str((len(x[x==0]), len(x[x==1]), len(x[x==2]))))

(draw, player1, player2) = (2, 5, 3)


In [6]:
game.active_player = player1

In [7]:
game.start_game()

Waiting for players
Starting game
Deep AI Player 1: Best move is: Move: G8, Horizontal, tiles: SNAILY, score: 26.0
Deep AI Player 1: Best move is: Move: H9, Vertical, tiles: ONSUIT, score: 8.0
Deep AI Player 1: Best move is: Move: J6, Horizontal, tiles: TEMED, score: 16.0
Deep AI Player 1: Best move is: Move: G13, Vertical, tiles: sAZ, score: 14.0
Deep AI Player 1: Best move is: Move: M3, Vertical, tiles: PRII, score: 20.0
Deep AI Player 1: Best move is: Move: D11, Horizontal, tiles: DHAL, score: 18.0
Deep AI Player 1: Best move is: Move: D8, Vertical, tiles: GLOE, score: 18.0
Deep AI Player 1: Best move is: Move: L2, Vertical, tiles: DOO, score: 16.0
Deep AI Player 1: Best move is: Move: H2, Horizontal, tiles: STAI, score: 8.0
Deep AI Player 1: Best move is: Move: F3, Horizontal, tiles: EWE, score: 13.0
Deep AI Player 1: Best move is: Move: A9, Horizontal, tiles: BAYE, score: 14.0
Deep AI Player 1: Best move is: Move: B8, Horizontal, tiles: POO, score: 18.0
Deep AI Player 1: Best move

In [6]:
moves

[Move object:
 Move: H8, Horizontal, tiles: WEIR, score: 14.0, Move object:
 Move: Exchange TRIE, Move object:
 Move: H8, Horizontal, tiles: TWEER, score: 18.0, Move object:
 Move: F8, Horizontal, tiles: WET, score: 12.0, Move object:
 Move: G8, Horizontal, tiles: TEE, score: 6.0, Move object:
 Move: D8, Horizontal, tiles: TWIRE, score: 18.0, Move object:
 Move: F8, Horizontal, tiles: WRITE, score: 16.0, Move object:
 Move: H6, Vertical, tiles: WEET, score: 14.0, Move object:
 Move: H8, Horizontal, tiles: WE, score: 10.0, Move object:
 Move: E8, Horizontal, tiles: WIRE, score: 14.0, Move object:
 Move: H5, Vertical, tiles: WERE, score: 14.0, Move object:
 Move: G8, Horizontal, tiles: ER, score: 4.0, Move object:
 Move: H8, Vertical, tiles: RETE, score: 8.0, Move object:
 Move: E8, Horizontal, tiles: WEET, score: 14.0, Move object:
 Move: H8, Horizontal, tiles: EWT, score: 12.0, Move object:
 Move: Exchange ETWII, Move object:
 Move: H8, Horizontal, tiles: TIER, score: 8.0, Move object:

In [17]:
super(type(player1), player1).best_move(moves)



<super: model.deepaiplayer.DeepAiPlayer,
        <model.deepaiplayer.DeepAiPlayer at 0x226eb648828>>

In [23]:
best_move_deep = player1.best_move(moves)
player1.rack.add_tiles(best_move_deep.tiles)
best_move_regular = super(type(player1), player1).best_move(moves)



Deep AI Player 1: Best move is: Move: H7, Vertical, tiles: WET, score: 12.0


In [22]:
player1.rack.add_tiles(best_move_deep.tiles)

In [19]:
player1.rack.add_tiles(best_move)

TypeError: object of type 'Move' has no len()

In [8]:
from fastai.transforms import *
trn_tfms,val_tfms = tfms_from_model('resnet18',256)

In [11]:
pwd

'C:\\code\\alexis'

In [22]:
img = Image.open('data/test/option_0000.png')
img.resize((256,256),Image.NEAREST)

im = trn_tfms(img)
preds = player1.learn.predict_array(im[None])

AttributeError: 'PngImageFile' object has no attribute 'shape'

In [4]:
player2.rack

Rack object containing the following tiles:
IIIOOQT

In [5]:
move = gui.parse_move_string('G8HQI')

In [6]:
print(move)

Move: G8, Horizontal, tiles: QI, forms word: , score: None


In [7]:
validator.is_valid(move)

True

In [8]:
tile_values = [LETTER_VALUES[(ord(t)-64)] for t in move.tiles]

In [9]:
move.score

22.0

In [10]:
tile_values

[10, 1]

In [11]:
squares_in_whole_word = move.row.squares_in_word(move.start_index)
squares_in_whole_word

array([7, 8], dtype=int64)

In [12]:
np.put(move.row.existing_letter_scores, move.played_squares, tile_values)

In [13]:
board

GameBoard object:
     A B C D E F G H I J K L M N O
   + - - - - - - - - - - - - - - - +
 1 | = . . ' . . . = . . . ' . . = |
 2 | . - . . . " . . . " . . . - . |
 3 | . . - . . . ' . ' . . . - . . |
 4 | ' . . - . . . ' . . . - . . ' |
 5 | . . . . - . . . . . - . . . . |
 6 | . " . . . " . . . " . . . " . |
 7 | . . ' . . . ' . ' . . . ' . . |
 8 | = . . ' . . Q I . . . ' . . = |
 9 | . . ' . . . ' . ' . . . ' . . |
10 | . " . . . " . . . " . . . " . |
11 | . . . . - . . . . . - . . . . |
12 | . . . - . . . ' . . . - . . . |
13 | ' . - . . . ' . ' . . . - . ' |
14 | . - . . . " . . . " . . . - . |
15 | = . . ' . . . = . . . ' . . = |
   + - - - - - - - - - - - - - - - +
     A B C D E F G H I J K L M N O

In [14]:
gui.describe_square('G9')

hook_squares:               False
word_multiplier:            1
letter_multiplier:          2
existing_letters:           none
existing_letter_scores:     0
this_row_crosschecks:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
this_row_crosschecks:       ABCDEFGHIJKLMNOPQRSTUVWXYZ
orthogonal_row_crosschecks: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
orthogonal_row_crosschecks: ABCDEFGHIJKLMNOPQRSTUVWXYZ
this_row_cross_scores:      -1
column_play_scores:         -1


In [15]:
game.execute_move(move)

In [16]:
row = move.row
row

row object:
 8 | = . . ' . * Q I * . . ' . . = |

In [17]:
row.hook_squares

array([False, False, False, False, False, False,  True, False, False,
        True, False, False, False, False, False, False, False])

In [18]:
gui.describe_square('I8')

hook_squares:               True
word_multiplier:            1
letter_multiplier:          1
existing_letters:           none
existing_letter_scores:     0
this_row_crosschecks:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
this_row_crosschecks:       ABCDEFGHIJKLMNOPQRSTUVWXYZ
orthogonal_row_crosschecks: [1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1]
orthogonal_row_crosschecks: NS
this_row_cross_scores:      -1
column_play_scores:         11


In [19]:
col = board.get_row(9,Direction.VERTICAL)

In [20]:
col

row object:
 I | . . ' . . . ' * ' . . . ' . . |

In [21]:
col.this_row_crosschecks

array([         0, 4294967295, 4294967295, 4294967295, 4294967295,
       4294967295, 4294967295, 4294967295, 4161290241, 4294967295,
       4294967295, 4294967295, 4294967295, 4294967295, 4294967295,
       4294967295,          0], dtype=uint32)

In [22]:
print(move)

Move: G8, Horizontal, tiles: QI, forms word: QI, score: 22.0


In [23]:
move

Move object:
Move: G8, Horizontal, tiles: QI, forms word: QI, score: 22.0

In [24]:
board

GameBoard object:
     A B C D E F G H I J K L M N O
   + - - - - - - - - - - - - - - - +
 1 | = . . ' . . . = . . . ' . . = |
 2 | . - . . . " . . . " . . . - . |
 3 | . . - . . . ' . ' . . . - . . |
 4 | ' . . - . . . ' . . . - . . ' |
 5 | . . . . - . . . . . - . . . . |
 6 | . " . . . " . . . " . . . " . |
 7 | . . ' . . . * * ' . . . ' . . |
 8 | = . . ' . * Q I * . . ' . . = |
 9 | . . ' . . . * * ' . . . ' . . |
10 | . " . . . " . . . " . . . " . |
11 | . . . . - . . . . . - . . . . |
12 | . . . - . . . ' . . . - . . . |
13 | ' . - . . . ' . ' . . . - . ' |
14 | . - . . . " . . . " . . . - . |
15 | = . . ' . . . = . . . ' . . = |
   + - - - - - - - - - - - - - - - +
     A B C D E F G H I J K L M N O

In [25]:
False is not None

True

In [26]:

None is not None

False

In [27]:
'CaT' in lex


True

In [28]:
x = [1,2,0,4,5]

In [29]:
y = np.where(x)

In [30]:
y

(array([0, 1, 3, 4], dtype=int64),)

In [31]:
x[0] = 0
x

[0, 2, 0, 4, 5]

In [32]:
y

(array([0, 1, 3, 4], dtype=int64),)

In [33]:
ord('@')

64

In [34]:
'a'.upper()

'A'

In [35]:
'hexact' in lex


True

In [36]:
'paramo' in lex


True

In [37]:
'overlya' in lex


False

In [38]:
gui.describe_square('G8')

hook_squares:               False
word_multiplier:            1
letter_multiplier:          1
existing_letters:           Q
existing_letter_scores:     10
this_row_crosschecks:       [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
this_row_crosschecks:       ABCDEFGHIJKLMNOPQRSTUVWXYZ
orthogonal_row_crosschecks: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
orthogonal_row_crosschecks: ABCDEFGHIJKLMNOPQRSTUVWXYZ
this_row_cross_scores:      -1
column_play_scores:         -1


In [39]:
move = gui.parse_move_string('G9VI')
move

Move object:
Move: G9, Vertical, tiles: I, forms word: Q, score: None

In [40]:
tile_values = [(LETTER_VALUES[(ord(t)-64)] if t.isupper() else LETTER_VALUES[0]) for t in move.tiles]
tile_values

[1]

In [41]:
squares_in_whole_word = move.row.squares_in_word(move.start_index)
squares_in_whole_word

array([8], dtype=int64)

In [42]:
empties = move.row.empty_squares(9)
empties

array([ 9, 10, 11, 12, 13, 14, 15], dtype=int64)

In [43]:
start_square = move.row.start_of_word(9)
start_square

8

In [44]:
end_square = BOARD_SIZE if len(empties) == 0 else empties[0]
end_square

9

In [45]:
tile_values

[1]

In [46]:
move.row.existing_letter_scores

array([ 0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int8)

In [47]:
move.played_squares

array([9], dtype=int64)

In [48]:
np.put(move.row.existing_letter_scores, move.played_squares, tile_values)

In [49]:
score = np.sum((move.row.existing_letter_scores * move.row.letter_multipliers)[squares_in_whole_word])
score

10

In [50]:
score *= np.prod(move.row.word_multipliers[move.played_squares])
score

10

In [51]:
np.sum(np.where(
            move.row.this_row_cross_scores != NO_CROSS_WORD,
            ((move.row.existing_letter_scores * move.row.letter_multipliers
              + move.row.this_row_cross_scores) * move.row.word_multipliers),
            np.zeros(17))[move.played_squares])

0.0

In [52]:
move.row.this_row_cross_scores

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [53]:
move.row.orthogonal_column_cross_scores != NO_CROSS_WORD

array([False, False, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False, False])

In [54]:
move.row.existing_letter_scores * move.row.letter_multipliers


array([ 0,  0,  0,  0,  0,  0,  0,  0, 10,  2,  0,  0,  0,  0,  0,  0,  0],
      dtype=int8)

In [55]:
move.row.orthogonal_column_cross_scores * move.row.word_multipliers


array([ 0, -1, -1, -1, -1, -1, -1, 10, -1, 10, -1, -1, -1, -1, -1, -1,  0])

In [56]:
move.row.word_multipliers


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0], dtype=int8)

In [57]:
score

10

In [58]:
game.active_player


In [59]:
game.validator

In [60]:
validator.is_valid(move)

True

In [61]:
move

Move object:
Move: G9, Vertical, tiles: I, forms word: QI, score: 12.0

In [64]:
player1.rack.score_of_remaining_tiles()

12

In [65]:
x  = [1,2,3]

In [66]:
not x

False

In [67]:
if x:
    print('blah')

blah


In [68]:
y = (1,2,3)

In [69]:
not y

False

In [70]:
y = ()

In [71]:
not y


True

In [73]:
import queue



In [74]:
x = np.full(17, None)

In [75]:
x


array([None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None], dtype=object)

In [86]:
x = [1,2,3]

In [77]:
y=[[7,8,9],[4,5,6],[3,4,5]]


In [78]:
y


[[7, 8, 9], [4, 5, 6], [3, 4, 5]]

In [90]:
import itertools
x.extend(itertools.chain.from_iterable(y))

In [91]:
x

[1, 2, 3, 7, 8, 9, 4, 5, 6, 3, 4, 5]